############################################################
# Dockerfile to build Flask App
# Based on
############################################################

# Set the base image
FROM debian:latest

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get update && apt-get install -y apache2 \
    libapache2-mod-wsgi-py3 \
    build-essential \
    python3 \
    python3-dev\
    python3-pip \
    vim \
 && apt-get clean \
 && apt-get autoremove \
 && rm -rf /var/lib/apt/lists/*


# Copy over and install the requirements
RUN mkdir -p  /var/www/html/prova/
COPY . /var/www/html/prova/

RUN pip install -r /var/www/html/prova/flask/requirements.txt


# Copy over the apache configuration file and enable the site
COPY ./prova.conf /etc/apache2/sites-available/prova.conf
RUN a2ensite prova
RUN a2enmod ssl

#Copy ssl file
COPY ./cert /var/www/html/prova/cert

# Copy over the wsgi file
COPY ./app.wsgi /var/www/html/app.wsgi

COPY ./app.py /var/www/html/prova/app.py


RUN a2dissite 000-default.conf
RUN a2ensite prova.conf

# LINK apache config to docker logs.
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/1 /var/log/apache2/error.log



WORKDIR /var/www/html/prova

CMD  /usr/sbin/apache2ctl -D FOREGROUND
